### PR TITLE
Add initial Docker compose configuration

### PR DESCRIPTION
**Pull request by tolbrino**
Refs https://github.com/hoprnet/hopr-devrel/issues/284

### CODE REVIEW

**Comment by nionis** [comment]
issue when running `make devkit-run`

```
Error response from daemon: manifest for gcr.io/hoprassociation/hopr-rpc-relay:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/hoprassociation/hopr-rpc-relay/manifests/latest".
```

I guess we don't have something pushed yet?

**Comment by tolbrino** [comment]
> issue when running `make devkit-run`
> 
> ```
> Error response from daemon: manifest for gcr.io/hoprassociation/hopr-rpc-relay:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/hoprassociation/hopr-rpc-relay/manifests/latest".
> ```
> 
> I guess we don't have something pushed yet?

Correct. I should have mentioned that. Use:

```
RELAY_VERSION=v0.0.1 make deveit-run
```

**Comment by nionis** [comment]
@tolbrino I can get it to build now, but when running it gets stuck in:

```
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:27Z [setup-local-cluster] Retrying command 2 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:32Z [setup-local-cluster] Retrying command 1 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:37Z [setup-local-cluster] Retrying command 0 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:37Z [setup-local-cluster] Wiping databases
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:37Z [setup-local-cluster] Cleaning up processes
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:38Z [setup-local-cluster] Wiping databases
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:38Z [setup-local-cluster] Cleaning up processes
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:44Z [setup-local-cluster] Removing cluster env file
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:44Z [setup-local-cluster] Wiping databases
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:44Z [setup-local-cluster] Cleaning up processes
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:44Z [setup-local-cluster] Removing cluster env file
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:49Z [setup-local-cluster] Removing cluster env file
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:48:55Z [setup-local-cluster] Retrying command 29 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:49:00Z [setup-local-cluster] Retrying command 28 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:49:05Z [setup-local-cluster] Retrying command 27 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:49:10Z [setup-local-cluster] Retrying command 26 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:49:15Z [setup-local-cluster] Retrying command 25 more time(s)
hopr-rpc-relay-devkit-pluto-1    | 22-09-29T07:49:20Z [setup-local-cluster] Retrying command 24 more time(s)
```

**Comment by nionis** [comment]
tried again and it works, can you also add a flag for rpc-relay logs? `DEBUG=hopr*`

**Review by nionis — APPROVED** [review]

**Pull request merged**
